build:
	sudo python3 topo.py 

startController:
	sudo python3 Controller.py


# loadp4prog:
# /

# terminals:
# 	../bin/create-terminal-windows.sh port1-veth3 port2-veth5 port3-veth7 port4-veth9

clean:
	rm \
	fd.json \
	fd.p4rt.txt \
	./log/*.log
	# ss-log.txt
